Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,14 +44,25 @@ jobs:
       env:
         KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
       run: |
-        echo "$KEYSTORE_BASE64" | base64 -d > $GITHUB_WORKSPACE/tv/keystore.p12
-        test -f $GITHUB_WORKSPACE/tv/keystore.p12 || exit 1
+        echo "$KEYSTORE_BASE64" | base64 -d > "$GITHUB_WORKSPACE/tv/keystore.p12"
+        if [ -f "$GITHUB_WORKSPACE/tv/keystore.p12" ]; then
+          echo "Keystore file $GITHUB_WORKSPACE/tv/keystore.p12 created successfully."
+        else
+          echo "Failed to create keystore file $GITHUB_WORKSPACE/tv/keystore.p12."
+          exit 1
+        fi
 
     - name: Debug keystore
       env:
         STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
       run: |
-        keytool -list -v -keystore $GITHUB_WORKSPACE/tv/keystore.p12 -storepass $STORE_PASSWORD -storetype PKCS12
+        echo "STORE_PASSWORD: $STORE_PASSWORD"
+        if [ -f "$GITHUB_WORKSPACE/tv/keystore.p12" ]; then
+          keytool -list -v -keystore "$GITHUB_WORKSPACE/tv/keystore.p12" -storepass "$STORE_PASSWORD" -storetype PKCS12
+        else
+          echo "Keystore file $GITHUB_WORKSPACE/tv/keystore.p12 does not exist."
+          exit 1
+        fi
 
     - name: Clean Gradle cache
       run: ./gradlew cleanBuildCache
@@ -64,10 +75,10 @@ jobs:
       run: |
         ./gradlew :tv:assembleRelease \
           --configuration-cache \
-          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/tv/keystore.p12 \
-          -Pandroid.injected.signing.store.password=$STORE_PASSWORD \
-          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
-          -Pandroid.injected.signing.key.password=$KEY_PASSWORD
+          -Pandroid.injected.signing.store.file="$GITHUB_WORKSPACE/tv/keystore.p12" \
+          -Pandroid.injected.signing.store.password="$STORE_PASSWORD" \
+          -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
+          -Pandroid.injected.signing.key.password="$KEY_PASSWORD"
 
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
